### ISSUE TITLE
Deprecation Warning and Helm Release Failure During Terraform Apply for EKS Cluster

### ISSUE THREAD

**Issue by qubitam** [aws-samples/ray-serve-whisper-streaming-on-eks#5]
I am getting the following issue when I run ./install.sh

Warning: Argument is deprecated
│ 
│   with module.eks.aws_iam_role.this[0],
│   on .terraform/modules/eks/main.tf line 293, in resource "aws_iam_role" "this":
│  293: resource "aws_iam_role" "this" {
│ 
│ The inline_policy argument is deprecated. Use the aws_iam_role_policy
│ resource instead. If Terraform should exclusively manage all inline policy
│ associations (the current behavior of this argument), use the
│ aws_iam_role_policies_exclusive resource as well.
╵
╷
│ Warning: Helm release "" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│ 
│   with module.eks_blueprints_addons.module.ingress_nginx.helm_release.this[0],
│   on .terraform/modules/eks_blueprints_addons.ingress_nginx/main.tf line 9, in resource "helm_release" "this":
│    9: resource "helm_release" "this" {
│ 
╵
╷
│ Error: 2 errors occurred:
│ 	* Internal error occurred: failed calling webhook "mservice.elbv2.k8s.aws": failed to call webhook: Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/mutate-v1-service?timeout=10s": no endpoints available for service "aws-load-balancer-webhook-service"
│ 	* Internal error occurred: failed calling webhook "mservice.elbv2.k8s.aws": failed to call webhook: Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/mutate-v1-service?timeout=10s": no endpoints available for service "aws-load-balancer-webhook-service"
│ 
│ 
│   with module.eks_blueprints_addons.module.ingress_nginx.helm_release.this[0],
│   on .terraform/modules/eks_blueprints_addons.ingress_nginx/main.tf line 9, in resource "helm_release" "this":
│    9: resource "helm_release" "this" {
│ 
╵
FAILED: Terraform apply of all modules failed

**Comment by lindarr915** [comment]
I reproduced the issue in my environment. 

### Workarond 
The workaround is to run `install.sh` again 

### Investigation 

Checking the output of Terraform and AWS Load Balancer Controller logs:

```
I1218 09:35:26.629214       1 leaderelection.go:248] attempting to acquire leader lease kube-system/aws-load-balancer-controller-leader...
2024/12/18 09:37:04 http: TLS handshake error from 10.12.53.182:39960: EOF
2024/12/18 09:37:04 http: TLS handshake error from 10.12.53.182:39970: read tcp 10.12.11.80:9443->10.12.53.182:39970: read: connection reset by peer
```

I suspect that it is some race conditions where the AWS Load Balancer Controller is not ready, but the the `Service` object of nginx ingress controller invokes the webhook endpoint but it failed. Retry again and it succeed. 

We are working on this issue.

**Comment by hustshawn** [comment]
I created a PR to avoid such issue, which mainly to disable the LBC and the Ingress https://github.com/aws-samples/ray-serve-whisper-streaming-on-eks/pull/6

**Comment by lindarr915** [comment]
Switched Auto Mode 
https://github.com/aws-samples/ray-serve-whisper-streaming-on-eks/pull/7
